import React from 'react';
import { GeneratedPage, BookConfig } from '../types';

interface PrintBookProps {
  pages: GeneratedPage[];
  config: BookConfig;
}

export const PrintBook: React.FC<PrintBookProps> = ({ pages, config }) => {
  return (
    <div className="print-only">
      {/* Cover Page */}
      <div className="book-page page-break bg-white relative overflow-hidden">
        <div className="absolute inset-0 border-[20px] border-slate-900 m-8 rounded-3xl opacity-10 pointer-events-none"></div>
        <div className="text-center z-10 p-12 max-w-2xl">
          <h1 className="text-8xl font-black text-slate-900 mb-8 uppercase tracking-widest font-comic">{config.theme}</h1>
          <div className="w-full h-1 bg-slate-900 my-8"></div>
          <p className="text-4xl text-slate-600 mb-4 font-comic">A Coloring Adventure For</p>
          <h2 className="text-7xl font-bold text-indigo-600 font-comic transform -rotate-2">{config.childName}</h2>
          <div className="mt-32 border-4 border-dashed border-slate-300 p-8 rounded-xl">
             <p className="text-slate-400 font-comic text-xl">Draw your self-portrait here!</p>
          </div>
        </div>
        <div className="absolute bottom-12 text-slate-400 font-medium">Generated by DreamLines AI</div>
      </div>

      {/* Content Pages */}
      {pages.map((page, index) => (
        <div key={page.id} className="book-page page-break relative">
          {page.imageUrl ? (
            <img src={page.imageUrl} alt={page.sceneDescription} className="border-4 border-black" />
          ) : (
            <div className="flex items-center justify-center h-full text-slate-300">Image Rendering Error</div>
          )}
          <div className="absolute bottom-8 right-8 text-xl font-comic text-slate-400">
            Page {index + 1}
          </div>
        </div>
      ))}
    </div>
  );
};
